apiVersion: 1

datasources:
  - name: Nouse-Database
    type: mysql
    url: db:3306
    database: nouse
    user: root
    password: rootPass
    editable: false
    jsonData:
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+